GET http://localhost:9000/boxes

###

GET http://localhost:9000/boxes/5f519fc4a63160a558b2b8b3

###

PATCH http://localhost:9000/boxes/5f519fc4a63160a558b2b8b3
Content-Type: application/json

{
    "img_src": "https://img.konami.com/yugioh/duel_links/en/box/power_of_bravery/images/banner.jpg?v=2"
}

###

POST http://localhost:9000/posts/
Content-Type: application/json

{
    "username": "Test",
    "title": "Why is this broken",
    "description": "This sucks.",
    "upvotes": 42
}

###

GET http://localhost:9000/posts/

###
PATCH http://localhost:9000/posts/5f585937da7c0b25bec0526d
Content-Type: application/json

{
    "image_src": "https://i.redd.it/i27lg8mp1yl51.jpg"
}

###
DELETE http://localhost:9000/posts/5f5662e7e69a93035284aeb5



###
POST http://localhost:9000/comments
Content-Type: application/json

{
    "postId": "5f55d884b2ccdcfd2d9f77c6",
    "username": "Kaiba",
    "body": "I ripped up 3 of those!"
}

###
GET http://localhost:9000/comments/

###

GET http://localhost:9000/comments/postId=/5f55cb8be945c1fd01aa6605

###

GET http://localhost:9000/posts/category=/Gameplay_Tips